### ISSUE TITLE
Odds and ends before v1.1

### ISSUE THREAD

**Issue by willpearse** [willpearse/pez#49]
* New version of scape
* Other new functions?
* Flag INND changes in new version (helpfile, changelog)
* Check help docs:
    * notes in shape going onto multiple paragraphs
    * PGLMM wrapper needs updating
    * ...likely many more

**Comment by willpearse** [comment]
* Aed doesn't get used anywhere!
* Not all metric citations are in place
* simpson's metric and that other weird one?
* Rao's entropy weird citation
* SESmpd citations are wrong too
* INND citation
* Remove unecessary classes in phy.structure
* get the randomisations Steve did into generic.metric

**Comment by cmtucker** [comment]
> Aed doesn't get used anywhere!

I think it should be used to calculate AED on its own, and also HAED ?
Those are both from the ecoPD/Cadotte canon of metrics.

**Comment by stevencarlislewalker** [comment]
"get the randomisations Steve did into generic.metric"

Do you want help with this?  To be honest I can't remember what these randomisations are.  I vaguely recall trying to better integrate some randomisation functions, but then giving up.

**Comment by willpearse** [comment]
Thanks for checking this guys! I'm very grateful!

@cmtucker - this is simply that I haven't written any code that actually uses the .aed function (or, if I have, I can't find it). Likewise for HAED - nothing to worry about though

@stevencarlislewalker thank you for the offer; don't worry too much about it since, if it's difficult, I'm simply not going to do it. I'm not even sure if the randomisations I'm thinking of are appropriate; this is just a reminder for me to check.
